[package]
name = "msw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "msw"
path = "src/main.rs"

[dependencies]
msw-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }
tracing.workspace = true
tracing-subscriber.workspace = true
